old_sound_rabbit_mq:
    connections:
        default:
            host: 'rabbitmq'
            port: 5672
            user: 'guest'
            password: 'guest'
            vhost: '/'
            lazy: false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: true # default false
        another:
            # A different (unused) connection defined by an URL. One can omit all parts,
            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
            # are given the value from the URL takes precedence.
            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
            url: 'amqp://guest:password@localhost:5672/vhost?lazy=1&connection_timeout=6'
        #producers:
        #    upload_picture:
        #        connection: default
        #        exchange_options: { name: 'upload-picture', type: direct }
        #        service_alias: my_app_service # no alias by default
        #consumers:
        #    upload_picture:
        #        connection: default
        #        exchange_options: { name: 'upload-picture', type: direct }
        #        queue_options: { name: 'upload-picture' }
        #        callback: upload_picture_service

    producers:
        send_email:
            class: App\Rabbit\Producer\MailSenderProducer
            connection: default
            exchange_options: { name: 'notification.v1.send_email', type: direct }

    consumers:
        send_email:
            connection: default
            exchange_options: { name: 'notification.v1.send_email', type: direct }
            queue_options: { name: 'notification.v1.send_email' }
            callback: App\Rabbit\Consumer\MailSenderConsumer