version: '3.8'
services:
  web:
    image: nginx:1.18-alpine
    volumes:
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      #- ./public:/var/www/html/public
      - ./public:/srv/app/public:ro
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=alexsav.test
      - NGINX_PORT=80
    restart: always
    depends_on:
      - php
      - db

  php:
    build: .
    restart: always
    volumes:
      - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      #- ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      #- .:/var/www/html
      - .:/srv/app
    depends_on:
      - db

  #composer:
  #  image: composer
  #  volumes:
  #    - .:/app
  #  command: install

  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      - POSTGRES_DB=alexsav
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 25000:5432
    volumes:
      - ./docker/postgres/conf/:/docker-entrypoint-initdb.d/
      - ./docker/postgres/data/:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    volumes:
      - ./docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: 'edKde9*dUdvpem5fGSkm4#fbgtJdj,l'
      #RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      #RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5673:5672
      - 15673:15672
    depends_on:
      - php
